### ISSUE TITLE
How do I send a packet while receiving?

### ISSUE THREAD

**Issue by vi** [meh/rust-tun#11]
How do I do full-duplex communication using `Device` without using `AsRawFd`, just with `std::io::Read` and `std::io::Write`?

Maybe `Device` should have `try_clone()`, so both copies can be sent to separate threads?

**Comment by kings-way** [comment]
@vi Check this
```pub fn split(self) -> (Reader, Writer)```
(https://docs.rs/tun/0.4.4/tun/platform/struct.Device.html#method.split)
