### ISSUE TITLE
fake into_raw_fd() for Device

### ISSUE THREAD

**Issue by kings-way** [meh/rust-tun#18]
Hey guys, 
it's good to have multiqueue support now, but it breaks trait ```IntoRawFd``` for ```Device```.
see here https://github.com/meh/rust-tun/blob/master/src/platform/linux/device.rs#L381

I think it may cause some trouble if someone calls ```into_raw_fd()``` to transfer the ownership of ```RawFd```, cause when ```Device``` is dropped, the underlying fd will be closed.

**Comment by meh** [comment]
@jibi :panda_face:
