### ISSUE TITLE
Support iOS and Android

### ISSUE THREAD

**Issue by eycorsican** [meh/rust-tun#21]
I made some changes to this crate and it works on iOS: https://github.com/eycorsican/rust-tun/commit/b5cdf6133bcf7465c7ffa0aabfe5d7ac54f73728

The idea is that on iOS and Android, we can create and configure a TUN interface in native code, then pass the `file descriptor` to `rust-tun` to create an async interface for reading/writing.

**Comment by meh** [comment]
Could you make a pull request so I can review it?

Also could you run `cargo fmt` in a separate commit so it's easier to review please?

**Comment by eycorsican** [comment]
I can make a PR for iOS, would you mind a PR with `rustfmt` apply to the whole project?

**Comment by meh** [comment]
You can put them both in the same PR as long as they're separate commits :panda_face:
