### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by omar391** [meh/rust-tun#27]
Any plan or timeline to support windows platform?

**Comment by meh** [comment]
Nope, I haven't really used Windows since Windows XP.

Pull requests welcome tho :panda_face:

**Comment by NN-Binary** [comment]
That would be such a great addition, I think most users can't implement this crate yet because of Windows non supported

**Comment by zonyitoo** [comment]
Maybe we could support it by [wintun](https://crates.io/crates/wintun).

**Comment by zonyitoo** [comment]
Here is a proposal about supporting Windows with [wintun](https://crates.io/crates/wintun). cc @iamwwc if you are interested.

Wintun is a good Tun driver on Windows designed for working in WireGuard.

1. Add a new `unix` module that wraps all android, ios, linux, macos, posix, and then make a new `windows` module in the platform.
2. `Configuration` on Windows will have optional fields `wintun_library_path`, `wintun_pool`
3.  Create a `Device` that contains `Adapter` and `Session`
4. For `AsyncDevice`, starts 2 async tasks with `spawn_blocking` and then all `read`s and `write`s will send and recv from channels to those tasks.

Some problems for discussion:

1. Should we keep the `wintun` as a singleton?
2. How to support multiple interfaces (adapters) within the same "pool"?
3. Should we support multiple "session"?

**Comment by mokhtarabadi** [comment]
Any news?

**Comment by amyipdev** [comment]
Bumping this since I think it could be really useful, I'm working on https://github.com/amyipdev/acc, after I found out pcap wouldn't work and I needed TUN, wintun support would be great.

**Comment by mokhtarabadi** [comment]
take a look at https://github.com/afula/tun2ostrich/tree/master/win_tun

**Comment by amyipdev** [comment]
@mokhtarabadi i was gonna use that, but tun2ostrich has now been removed from github...

**Comment by omar391** [comment]
@amyipdev this one: https://github.com/lemos1235/tun2ostrich ?

**Comment by amyipdev** [comment]
@omar391 thanks

**Comment by M0dEx** [comment]
Any updates?

I could really use Windows support in my project [Quincy](https://github.com/M0dEx/quincy).

I would love to help with anything I can to get this done in the next couple of weeks.

**Comment by mokhtarabadi** [comment]
@YosefUT can you help to add support for windows?

**Comment by xmh0511** [comment]
Any news?

**Comment by M0dEx** [comment]
This can be closed now, as Windows support has been added, correct?

**Comment by amyipdev** [comment]
Seconding @M0dEx's request to close
