### ISSUE TITLE
ios15

### ISSUE THREAD

**Issue by 50611** [meh/rust-tun#35]
self?.packetFlow.value(forKeyPath: "socket.fileDescriptor") as! Int32
in ios15 is not use

**Comment by bipo123** [comment]
how to fix it??

**Comment by superben2010** [comment]
let tunFd = self?.packetFlow.value(forKeyPath: "socket.fileDescriptor") as! Int32
GOT:
Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by EbrahimTahernejad** [comment]
add this header:
https://github.com/EbrahimTahernejad/Tun2SocksKit/blob/3036fab88eda42e04dfcf86318a94b9f83a72ab2/Sources/Tun2SocksKitC/Tun2SocksKitC.h

Then use this property to get the fd:
https://github.com/EbrahimTahernejad/Tun2SocksKit/blob/3036fab88eda42e04dfcf86318a94b9f83a72ab2/Sources/Tun2SocksKit/Tunnel.swift#L7
