### ISSUE TITLE
Add support to construct `TunPacket` from `Bytes` directly.

### ISSUE THREAD

**Issue by yiransheng** [meh/rust-tun#81]
Code pointer:
https://github.com/meh/rust-tun/blob/e762c419d71438e67379f9b2fed89b5cb835cc6a/src/async/codec.rs#L77C1-L80C2

`TunPacket` already stores the packet internally using `bytes::Bytes`, but it can only be constructed from a `Vec` via `TunPacket::new`. It would be nice to have a way (either a method of a `From` trait impl) to construct a `TunPacket` from `Bytes` directly, without going through the extra cloning in `Bytes -> Vec -> Bytes`.

**Comment by xmh0511** [comment]
Fixed by https://github.com/ssrlive/rust-tun/pull/5, you can switch to tun2, which is actively maintaining.
