### ISSUE TITLE
Project co-author recruitment

### ISSUE THREAD

**Issue by zonyitoo** [meh/rust-tun#90]
`tun` is a great project used by many project. There are many issues and PRs are still waiting for discussion and reviews.

After contacted with @meh on E-mail, I found that he is getting sicker and sicker (pray for @meh ). Here I opened an issue to help for recruiting co-authors, who can help reviewing and even publishing codes to crates.io.

**Comment by zonyitoo** [comment]
@xmh0511 @ssrlive , or anyone interested?

**Comment by xmh0511** [comment]
Of course.

**Comment by ssrlive** [comment]
Can you add someone as publisher? If it's yes, I'd love to join.

**Comment by ssrlive** [comment]
In this project, I have wasted too many time.

**Comment by ssrlive** [comment]
Can you add someone as publisher? If it's yes, I'd love to join.
In this project, I have wasted too many time.
You can ask @meh transform this project to you @zonyitoo or me, thus we no longer feel of submitting patches.

**Comment by ssrlive** [comment]
Can you add someone as publisher? If it's yes, I'd love to join. 
In this project, I have wasted too many time.
You can ask @meh to transfer this project to you @zonyitoo or me. thus we no longer feel afraid of submitting patches.

**Comment by tubzby** [comment]
Feel sorry to hear that.

**Comment by zonyitoo** [comment]
I have lost contact with @meh for a long time. Could anyone have any other way to reach out of him?

**Comment by meh** [comment]
I was extremely sick for the past two years, turns out the entire kitchen of the flat I moved to was mold infested and I'm allergic to it, recently found out and destroyed the mold, so I'm slowly coming back to life. It will still take months for my body to recover, is anyone still interested in taking up the mantle?

**Comment by ssrlive** [comment]
Congratulations on your recovery from your illness. @meh 
I hope you'll add me as a contributor and publisher. Thank you so much.
I've actually maintained the fork `tun2` for a year now, but I still hope to continue maintaining `tun`.

**Comment by appcypher** [comment]
@meh Just learning about this project, literally 10 minutes ago and thought it was such an amazing project. I’m really sorry to hear about what you’ve been through. That sounds like an intense ordeal, but it’s great you found the cause. 

I’m glad to hear you’re on the road to recovery.

**Comment by meh** [comment]
> Congratulations on your recovery from your illness. @meh I hope you'll add me as a contributor and publisher. Thank you so much. I've actually maintained the fork `tun2` for a year now, but I still hope to continue maintaining `tun`.

It is done, thank you :panda_face:

**Comment by ssrlive** [comment]
Thanks, I'll merge my branch into this repo sooner.
> It is done, thank you 🐼

**Comment by meh** [comment]
Noice, no rush, considering I've been dormant for a long time :P

But yeah people, do not underestimate the mold, and do not trust the fungus, I had absolutely zero respiratory symptoms, just chronic fatigue, extreme brain fog, sleep issues, skin issues and a seizure.

If you get weirdly chronically sick and all the tests come out negative, find the mycelia.

**Comment by zonyitoo** [comment]
@ssrlive I would suggest to separate the new features in tun2 to multiple independent PRs, better for reviewing.
